Repository gong-clone/programmers-clone, pull requests merged in 2020-09, with the labels that each got.

#5 베이스 코드 작성 PR
  .env
  .eslintignore
  .eslintrc.js
  .firebaserc
  .github/workflows/ci.yml
  .gitignore
  .storybook/main.js
  .storybook/preview.tsx
  LICENSE
  README.md
  firebase.json
  firestore.indexes.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/Application/Providers.tsx
  src/Application/Routes.tsx
  src/Application/Store.ts
  src/Application/Theme.ts
  src/Application/firebaseConfig.ts
  src/Application/index.tsx
  src/Components/Layout/index.tsx
  src/Compositions/.gitkeep
  src/Features/.gitkeep
  src/Hooks/.gitkeep
  src/Pages/Main/Main.stories.tsx
  src/Pages/Main/Main.test.tsx
  src/Pages/Main/index.tsx
  src/Types/theme.ts
  src/Utils/.gitkeep
  src/__fixtures__/.gitkeep
  src/index.tsx
  src/react-app-env.d.ts
  src/serviceWorker.ts
  src/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: 개발

#11 add storybook chromatic CI/CD #10
  .github/workflows/storybook.yml
  package.json
  src/Application/Application.test.tsx
  src/Application/Providers.tsx
  src/Components/Layout/Layout.stories.tsx
  src/Components/Layout/index.tsx
  src/Pages/Main/Main.stories.tsx
  src/Pages/Main/Main.test.tsx
  src/Pages/Main/index.tsx
  yarn.lock
Labels: 개발

#16 [#14] add button component
  src/Application/Theme.ts
  src/Components/Button/Button.stories.tsx
  src/Components/Button/index.tsx
  src/Types/theme.ts
Labels: 개발

#18 [#17] change ci branch for chromatic deploy
  .github/workflows/storybook.yml
Labels: 제안

#26 close #24 - add global style
  package.json
  src/Application/Providers.tsx
  src/Application/Theme.ts
  src/Application/globalStyle.ts
  src/Types/theme.ts
Labels: 개발, 버그

#31 [#30]Add globalStyle attribute
  src/Application/globalStyle.ts
Labels: 개발, 중복

#43 Fix directory name bug
  src/Application/Theme.ts
  src/Compositions/CompetitionSection/ListCompetitionSection/SwiperSlide/ItemWrap/ItemBadgeState/ItemBadgeLabel/ItemBadgeLabel.stories.tsx
  src/Compositions/CompetitionSection/ListCompetitionSection/SwiperSlide/ItemWrap/ItemBadgeState/ItemBadgeLabel/index.tsx
  src/Compositions/CompetitionSection/ListCompetitionSection/SwiperSlide/ItemWrap/ItemBadgeState/ItemBadgeState.stories.tsx
  src/Compositions/CompetitionSection/ListCompetitionSection/SwiperSlide/ItemWrap/ItemBadgeState/index.tsx
Labels: 버그

#37 Feature/#28/add navbar
  src/Compositions/HeroSection/HeroSection.stories.tsx
  src/Compositions/HeroSection/HeroWrap/DescHero/BtnStart/BtnStart.stories.tsx
  src/Compositions/HeroSection/HeroWrap/DescHero/BtnStart/index.tsx
  src/Compositions/HeroSection/HeroWrap/DescHero/Cap/SubTitle.stories.tsx
  src/Compositions/HeroSection/HeroWrap/DescHero/Cap/index.tsx
  src/Compositions/HeroSection/HeroWrap/DescHero/DescHero.stories.tsx
  src/Compositions/HeroSection/HeroWrap/DescHero/SubTitle/SubTitle.stories.tsx
  src/Compositions/HeroSection/HeroWrap/DescHero/SubTitle/index.tsx
  src/Compositions/HeroSection/HeroWrap/DescHero/Title/Title.stories.tsx
  src/Compositions/HeroSection/HeroWrap/DescHero/Title/index.tsx
  src/Compositions/HeroSection/HeroWrap/DescHero/index.tsx
  src/Compositions/HeroSection/HeroWrap/HeroWrap.stories.tsx
  src/Compositions/HeroSection/HeroWrap/ImgHero/ImgHero.stories.tsx
  src/Compositions/HeroSection/HeroWrap/ImgHero/index.tsx
  src/Compositions/HeroSection/HeroWrap/index.tsx
  src/Compositions/HeroSection/index.tsx
  src/Compositions/Navbar/Navbar.stories.tsx
  src/Compositions/Navbar/NavbarBrand/Logo/Logo.stories.tsx
  src/Compositions/Navbar/NavbarBrand/Logo/index.tsx
  src/Compositions/Navbar/NavbarBrand/NavbarBrand.stories.tsx
  src/Compositions/Navbar/NavbarBrand/index.tsx
  src/Compositions/Navbar/NavbarCollapse/NavItem/NavItem.stories.tsx
  src/Compositions/Navbar/NavbarCollapse/NavItem/index.tsx
  src/Compositions/Navbar/NavbarCollapse/NavbarCollapse.stories.tsx
  src/Compositions/Navbar/NavbarCollapse/NavbarGlobal/NavbarGlobal.stories.tsx
  src/Compositions/Navbar/NavbarCollapse/NavbarGlobal/index.tsx
  src/Compositions/Navbar/NavbarCollapse/UserMenu/UserMenu.stories.tsx
  src/Compositions/Navbar/NavbarCollapse/UserMenu/index.tsx
  src/Compositions/Navbar/NavbarCollapse/index.tsx
  src/Compositions/Navbar/index.tsx
Labels: 개발
